version: "3.8"
services:
  web:
    image: highfivesoftware/dashboard
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .env
    environment:
      "JWT__Secret": "some-secret-key-that-should-be-overwritten"
      "ConnectionStrings:default": "Server=db;Port=5432;Database=dashboard;Username=dashboard;Password=dashboard"
      "AllowedOrigins": "https://highfivesoftware.tk"