name: Manual Deployment
on: [ workflow_dispatch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@master
        
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
#          envs: FOO,BAR
          script: |
            cd Dashboard
            git pull
            docker-compose up -d --build 
